server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.95.87:3306/worker?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: dev
    password: dev123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
    database: 0
    host: 47.101.204.254
    port: 6479
    password: dev123
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timout: 3000

#微信公众号配置
wx:
  accessToken:
    url: 1
  appid: 1
  appsecret: 1
  oauth:
    getCode:
      url: 1
    redirect:
      url: 1
    getAccessToken:
      url: 1
    userInfo:
      url: 1
